apps/acticle/urls.py
from django.conf.urls import url

from .views import ArticleInfo, ArticleListView, AddComment

urlpatterns = [
    url(r'^(?P<article_id>\d+)/$', ArticleInfo.as_view(), name='article_info'),

    url(r'^list/$', ArticleListView.as_view(), name='article_list'),

    url(r'^add_comment/$', AddComment.as_view(), name='add_comment'),

    url(r'^fav/', ArticleListView.as_view(), name='fav'),

]

blog/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
import xadmin
from .settings import MEDIA_ROOT, STATIC_ROOT
from django.views.static import serve

from users.views import IndexView, LoginView, RegisterView, LogoutView, AboutView, FriendView, \
    PersonView, AddMessage, UploadImageView, UpdatePwdView, UpdateEmailView

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)', serve, {'document_root': STATIC_ROOT}),
    url(r'^ueditor/', include('DjangoUeditor.urls')),

    # 登录等相关
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    # 首页不重要
    url(r'^about/', AboutView.as_view(), name='about'),
    url(r'^friend/', FriendView.as_view(), name='friend'),

    # 个人资料
    url(r'^person/', PersonView.as_view(), name='person'),
    url(r'^upload_image/$', UploadImageView.as_view(), name='upload_image'),
    url(r'^update_pwd/$', UpdatePwdView.as_view(), name='update_pwd'),
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),

    url(r'^add_message/$', AddMessage.as_view(), name='add_message'),

    url(r'^article/', include('acticle.urls', namespace='article'))
]

handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'
handler403 = 'users.views.permission_denied'

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

apps/operation/models.py
from datetime import datetime

from django.db import models

from users.models import UserProfile
from acticle.models import Article


class Message(models.Model):
    """对网站留言"""
    user = models.ForeignKey(UserProfile, null=True, blank=True, verbose_name='留言用户')
    email = models.EmailField(verbose_name='邮箱')
    content = models.TextField(verbose_name='内容')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '留言'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user.username


class Publish(models.Model):
    """用户发表文章"""
    user = models.ForeignKey(UserProfile, null=True, blank=True, verbose_name='发表用户')
    article = models.ForeignKey(Article, null=True, blank=True, verbose_name='文章')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '发表文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{0}-to-{1}".format(self.user.username, self.article.name)


class Comment(models.Model):
    """用户对文章进行评论"""
    user = models.ForeignKey(UserProfile, null=True, blank=True, verbose_name='评论用户')
    article = models.ForeignKey(Article, null=True, blank=True, verbose_name='被评论文章')
    content = models.TextField(verbose_name='内容', default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{0}-to-{1}".format(self.user.username, self.article.name)


class UserFav(models.Model):
    """收藏"""
    user = models.ForeignKey(UserProfile, verbose_name='收藏用户')
    article = models.ForeignKey(Article, verbose_name='被收藏文章')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '收藏'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{0}-to-{1}".format(self.user.username, self.article.name)

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/about.html
{% extends 'base.html' %}
{% block title %}关于我们{% endblock %}
{% block content %}
      <div class="content-block contact-content">
        <h2 class="title"><strong>联系站长</strong></h2>
        <p><span>站长QQ：</span><a href="">757235517</a></p>
        <p><span>站长信箱：</span><a href="mailto:757235517@qq.com">757235517@qq.com</a></p>
      </div>
      <div class="content-block comment">

        <h2 class="title"><strong>添加留言</strong></h2>

        <form action="{% url 'add_message' %}" method="post" class="form-inline" id="comment-form">
          <div class="comment-title">
            <div class="form-group">
              <label for="messageName">姓名：</label>
              <input type="text" name="user" class="form-control" id="messageName"
              {% if request.user.is_authenticated %}value="{{ request.user.username }}" {% else %}placeholder="请输入姓名" {% endif %}>
            </div>
            <div class="form-group">
              <label for="messageEmail">邮箱：</label>
              <input type="email" name="email" class="form-control" id="messageEmail"
              {% if request.user.is_authenticated %}value="{{ request.user.email }}" {% else %}placeholder="请输入邮箱" {% endif %}>
            </div>
          </div>
          <div class="comment-form">
            <textarea placeholder="在此处填写留言内容" name="content"></textarea>

            <div class="comment-form-footer">
                {% if not request.user.is_authenticated %}
                    <div class="comment-form-text">请先
                        <a href="{% url 'login' %}">登录</a> 或 <a href="{% url 'register' %}">注册</a>，也可匿名留言 </div>
                {% endif %}
              <div class="comment-form-btn">
                <button type="submit" class="btn btn-default btn-comment">提交留言</button>
              </div>
            </div>
          </div>
        {% csrf_token %}
        </form>

        <div class="content-block comment-content">
          <h2 class="title"><strong>最新留言</strong></h2>
          <ul>
              {% for message in new_message %}
                <li>
                    <span class="text"><strong>{{ message.user.username }}</strong> ({{ message.add_time }}) 留言：<br />
                    {{ message.content }}</span></li>
              {% endfor %}
          </ul>
        </div>
      </div>
{% endblock %}

templates/content.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ article.name }}{% endblock %}
{% block content %}
      <header class="news_header">
        <h2>{{ article.name }}</h2>
        <ul>
          <li>发布于 {{ article.add_time }}</li>
          <li>栏目：<a href="" title="" >{{ article.column }}</a></li>
          <li>来源：<a href="" title="" >{{ article.resouce }}</a></li>
          <li>共 <strong>{{ article.see_num }}</strong> 人围观 </li>
          <li><strong>{{ article.see_unkown_num }}</strong> 个不明物体</li>
        </ul>
      </header>
      <article class="news_content">
        {% autoescape off %}
            {{ article.content }}
        {% endautoescape %}
      </article>

      <div class="tags news_tags">标签：
          {% for tag in tags %}
            <span data-toggle="tooltip" data-placement="bottom" title="查看关于 {{ tag.name }} 的文章">
              <a href="{% url 'article:article_list' %}?tag={{ tag.name }}">{{ tag.name }}</a>
            </span>
          {% endfor %}
      </div>

      <div class="content-block related-content visible-lg visible-md">
        <h2 class="title"><strong>相关推荐</strong></h2>
        <ul>
            {% for relate_article in relate_articles %}
                <li>
                    <a target="_blank" href="{% url 'article:article_info' relate_article.id %}"><img src="{{ MEDIA_URL }}{{ relate_article.image }}" alt="">
                        <h3> {{ relate_article.name }} </h3>
                    </a>
                </li>
            {% endfor %}
        </ul>
      </div>


      <div class="content-block comment">
        <h2 class="title"><strong>评论</strong></h2>
        {% if request.user.is_authenticated %}
        <form action="{% url 'article:add_comment' %}" method="post" class="form-inline" id="comment-form">
          <div class="comment-form">
            <input type="hidden" name="article_id" value="{{ article.id }}">
            <textarea placeholder="你的评论可以一针见血" name="content"></textarea>
            <div class="comment-form-footer">
              <div class="comment-form-text">请先评论 </div>
              <div class="comment-form-btn">
                <button type="submit" class="btn btn-default btn-comment">提交评论</button>
              </div>
            </div>
          </div>
        {% csrf_token %}
        </form>
        {% endif %}

        <div class="comment-content">
          <ul>
              {% for comment in comments %}
                <li>
                    <span class="face"><img src="{{ MEDIA_URL }}{{ comment.user.image }}" alt=""></span>
                    <span class="text"><strong>{{ comment.user.username }}</strong> ({{ comment.add_time|date:'Y-m-d' }}) 说：<br />{{ comment.content }}</span></li>
              {% endfor %}
          </ul>
        </div>
      </div>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript">
    //相关推荐
    $(function(){
        $(".related-content ul li").hover(function(){
            $(this).find("h3").show();
        },function(){
            $(this).find("h3").hide();
        });
    });
    //ajax更新点赞值
    $(function(){
        $(".content .zambia a").click(function(){
            var zambia = $(this);
            var id = zambia.attr("rel"); //对应id
            zambia.fadeOut(1000); //渐隐效果
            $.ajax({
                type:"POST",
                url:"zambia.php",
                data:"id="+id,
                cache:false, //不缓存此页面
                success:function(data){
                    zambia.html(data);
                    zambia.fadeIn(1000); //渐显效果
                }
            });
            return false;
        });
    })
    </script>
{% endblock %}

templates/friendly.html
{% extends 'base.html' %}
{% block title %}站长收藏{% endblock %}
{% block content %}
      <div class="content-block friendly-content row">
        <h2 class="title"><strong>站长收藏</strong></h2>
        {% for friend in friends %}
            <div class="col-md-4 col-xs-6">
                <span data-toggle="tooltip" data-placement="bottom" title="点击进入 {{ friend.title }}  站点">
                    <a href="{{ friend.url }}">{{ friend.title }}</a>
                </span>
            </div>
        {% endfor %}
      </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}index-我的博客{% endblock %}
{% block content %}
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel"> <!--banner-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        {% for banner in banners %}
              <div class="item {% if forloop.counter == 1 %}active{% endif %}">
                  <a href="{{ banner.url }}" target="_blank"><img src="{{ MEDIA_URL }}{{ banner.image }}" alt="" /></a>
                  <div class="carousel-caption"> {{ banner.title }} </div>
                  <span class="carousel-bg"></span>
              </div>
        {% endfor %}
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span class="sr-only">Next</span>
        </a>
    </div>
  <!--/banner-->

  <div class="content-block hot-content hidden-xs">
    <h2 class="title"><strong>热门排行</strong></h2>
    <ul>
        {% for hots_article in hots_articles %}
              <li class="{% if forloop.counter == 1 %}large{% endif %}">
                  <a href="{% url 'article:article_info' hots_article.id %}" target="_blank">
                      <img src="{{ MEDIA_URL }}{{ hots_article.image }}" alt="">
                      <h3> {{ hots_article.name }} </h3>
                  </a>
              </li>
        {% endfor %}
    </ul>
  </div>

  <div class="content-block new-content">
    <h2 class="title"><strong>最新文章</strong></h2>
    <div class="row">
        {% for new_article in new_articles %}
            <div class="news-list">
                <div class="news-img col-xs-5 col-sm-5 col-md-4">
                    <a target="_blank" href="{% url 'article:article_info' new_article.id %}">
                        <img src="{{ MEDIA_URL }}{{ new_article.image }}" alt="">
                    </a>
                </div>
                <div class="news-info col-xs-7 col-sm-7 col-md-8">
                  <dl>
                    <dt> <a href="{% url 'article:article_info' new_article.id %}" target="_blank" > {{ new_article.name }} </a> </dt>
                    <dd>
                        <span class="name"><a href="" title="由 {% for author in new_article.publish_set.all %}{{ author.user  }}{% endfor %} 发布" rel="author">
                            {% for author in new_article.publish_set.all %}{{ author.user  }}{% endfor %}</a>
                        </span>
                        <span class="identity"></span> <span class="time">
                            {% for author in new_article.publish_set.all %}{{ author.add_time|date:'Y-n-d'  }}{% endfor %}
                        </span>
                    </dd>
                    <dd class="text">{{ new_article.brief }}</dd>
                  </dl>
                  <div class="news_bot col-sm-7 col-md-8">
                      <span class="tags visible-lg visible-md">
                          {% for tag in new_article.tags.all %}<a href="javscript:;">{{ tag.name }}</a>{% endfor %}
                      </span>
                      <span class="look"> 共 <strong>{{ new_article.see_num }}</strong> 人围观，
                          发现 <strong> {{ new_article.see_unkown_num }} </strong> 个不明物体 </span>
                  </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="news-more" id="">
        <a href="{% url 'article:article_list' %}">查看更多</a>
    </div>
  </div>
</div>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="content-block new-content">
    <h2 class="title"><strong>最新文章</strong></h2>
    <div class="row">
        {% for article in articles.object_list %}
            <div class="news-list">
                <div class="news-img col-xs-5 col-sm-5 col-md-4">
                    <a target="_blank" href="{% url 'article:article_info' article.id %}">
                        <img src="{{ MEDIA_URL }}{{ article.image }}" alt="">
                    </a>
                </div>
                <div class="news-info col-xs-7 col-sm-7 col-md-8">
                  <dl>
                    <dt> <a href="{% url 'article:article_info' article.id %}" target="_blank" > {{ article.name }} </a> </dt>
                    <dd>
                        <span class="name"><a href="" title="由 {% for author in article.publish_set.all %}{{ author.user  }}{% endfor %} 发布" rel="author">
                            {% for author in article.publish_set.all %}{{ author.user  }}{% endfor %}</a>
                        </span>
                        <span class="identity"></span> <span class="time">
                            {% for author in article.publish_set.all %}{{ author.add_time|date:'Y-n-d'  }}{% endfor %}
                        </span>
                    </dd>
                    <dd class="text">{{ article.brief }}</dd>
                  </dl>
                  <div class="news_bot col-sm-7 col-md-8">
                      <span class="tags visible-lg visible-md">
                          {% for tag in article.tags.all %}<a href="javscript:;">{{ tag.name }}</a>{% endfor %}
                      </span>
                      <span class="look"> 共 <strong>{{ article.see_num }}</strong> 人围观，
                          发现 <strong> {{ article.see_unkown_num }} </strong> 个不明物体 </span>
                  </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="quotes pagination" style="margin-top:15px">
        {% if articles.has_previous %}
            <a href="?{{ articles.previous_page_number.querystring }}" class="prev">上一页</a>
        {% endif %}
        {% for page in articles.pages %}
            {% if page %}
                {% ifequal page articles.number %}
                    <span class="current page">{{ page }}</span>
                {% else %}
                    <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                {% endifequal %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        {% if articles.has_next %}
            <a href="?{{ articles.next_page_number.querystring }}" class="next">下一页</a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
		<meta charset="utf-8">
		<link href="{% static 'css/reglogin.css' %}" rel='stylesheet' type='text/css' />
		<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class="main">
		<div class="header" >
			<h1>Login!</h1>
		</div>
		<p></p>
			<form method="post" action="{% url 'login' %}">
				<ul class="right-form">
					<h2>Login:</h2>
					<li><input type="text" name="username" placeholder="Username" required/></li>
					<li><input type="password" name="password" placeholder="Password" required/></li>
                    <div>
                        {% for key,error in login_form.errors.items %}{{ error }}{% endfor %}
                        {{ msg }}
                    </div>
					<input type="submit" value="Login" >
					<div class="clear"> </div>
				</ul>
				<div class="clear"> </div>
                {% csrf_token %}
			</form>
	</div>
</body>
</html>

templates/reg.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <link href="{% static 'css/reglogin.css' %}" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
	<div class="main">
		<div class="header" >
			<h1>Create a Free Account!</h1>
		</div>
		<p></p>
			<form method="post" action="{% url 'register' %}">
				<ul class="right-form">
					<h2>Account:</h2>
					<li><input name="username" type="text" value="{{ register_form.username.value }}" placeholder="Username" required/></li>
					<li><input name="email" value="{{ register_form.email.value }}" type="email" placeholder="Email" required/></li>
					<li><input name="password1" value="{{ register_form.password1.value }}" type="password" placeholder="password" required/></li>
					<li><input name="password2" value="{{ register_form.password2.value }}" type="password" placeholder="password" required/></li>
                    <div>
                        {% for key,error in register_form.errors.items %}{{ error }}{% endfor %}
                        {{ msg }}
                    </div>
					<input type="submit" value="Register" >
					<div class="clear"> </div>
				</ul>
				<div class="clear"> </div>
                {% csrf_token %}
			</form>
	</div>
</body>
</html>

templates/zambia.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>点赞</title>
</head>

<body>
<script type="text/javascript">
//向后台zambia.php发送ajax请求，请求响应成功后，更新原有的数值
$(function(){   
    $(".content .zambia a").click(function(){   
        var zambia = $(this);   
        var id = zambia.attr("rel"); //对应id   
        zambia.fadeOut(1000); //渐隐效果   
        $.ajax({   
            type:"POST",   
            url:"zambia.php",   
            data:"id="+id,   
            cache:false, //不缓存此页面   
            success:function(data){   
                zambia.html(data);   
                zambia.fadeIn(1000); //渐显效果   
            }   
        });   
        return false;   
    });   
})
</script>
</body>
</html>